name: Run KeyBoxer Direct

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-keyboxer:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: List all files (diagnostic)
        run: |
          ls -la
          echo "Checking for pyproject.toml content:"
          if [ -f "pyproject.toml" ]; then
            cat pyproject.toml
          fi
      
      - name: Install direct dependencies
        run: |
          pip install requests python-dotenv beautifulsoup4 lxml
          # Add any other packages you know are needed
          
      - name: Create required directories
        run: |
          mkdir -p keys
          touch cache.txt
      
      - name: Create .env file with GitHub token
        run: |
          echo "GITHUB_TOKEN=${{ secrets.PAT_TOKEN }}" > .env
        
      - name: Run KeyBoxer
        run: |
          python ./keyboxer.py
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          
      - name: List results
        run: |
          echo "KeyBoxer execution complete"
          echo "Contents of keys directory:"
          ls -la keys/ || echo "No keys directory found"
