name: Run KeyBoxer with Telegram Crawler

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  id-token: write

jobs:
  run-keyboxer:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Increased timeout for Telegram crawling
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install requests python-dotenv beautifulsoup4 lxml cryptography telethon aiohttp asyncio
      
      - name: Create required directories
        run: |
          mkdir -p keys
          mkdir -p telegram_session
          touch cache.txt
      
      - name: Create .env file with tokens
        run: |
          echo "GITHUB_TOKEN=${{ secrets.PAT_TOKEN }}" > .env
          echo "TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }}" >> .env
          echo "TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }}" >> .env
          echo "TELEGRAM_PHONE=${{ secrets.TELEGRAM_PHONE }}" >> .env
          echo "TELEGRAM_SESSION_STRING=${{ secrets.TELEGRAM_SESSION_STRING }}" >> .env
          echo "GH_TOKEN=${{ github.token }}" >> .env
      
      - name: Run Telegram crawler for keyboxes
        continue-on-error: true  # Continue workflow even if this step fails
        run: |
          python - <<EOF
          import os
          import asyncio
          import sqlite3
          import json
          import logging
          from pathlib import Path
          from telegram_crawler import setup_database, add_channel, one_time_scrape
          
          # Setup logging
          logging.basicConfig(level=logging.INFO)
          
          # DIRECTLY SET THE SESSION STRING
          os.environ["TELEGRAM_SESSION_STRING"] = """${{ secrets.TELEGRAM_SESSION_STRING }}"""
          
          # Initialize database
          setup_database()
          
          # Add default channels to track
          DEFAULT_CHANNELS = [
              "-1001796581959",
              "-1002111293060",
              "-1002376413293",
              "-1002360732129"
          ]
          
          # If TELEGRAM_CHANNELS is set in secrets, use those instead
          telegram_channels = os.environ.get('TELEGRAM_CHANNELS')
          if telegram_channels:
              channels_to_add = json.loads(telegram_channels)
              if not channels_to_add:  # Check if the list is empty
                  channels_to_add = DEFAULT_CHANNELS
                  print("Empty channel list in environment, using defaults")
              else:
                  print(f"Using {len(channels_to_add)} channels from environment")
          else:
              channels_to_add = DEFAULT_CHANNELS
              print("No channels in environment, using defaults")
          
          # Add all channels
          for channel in channels_to_add:
              add_channel(channel)
              print(f"Added channel {channel} for tracking")
          
          # Run one-time scrape
          asyncio.run(one_time_scrape())
          
          # Show summary of findings
          db_path = Path("telegram_data.db")
          if db_path.exists():
              conn = sqlite3.connect(db_path)
              c = conn.cursor()
              
              c.execute('SELECT COUNT(*) FROM keyboxes WHERE valid = 1')
              result = c.fetchone()
              valid_count = result[0] if result is not None else 0
              
              c.execute('SELECT channel_name, COUNT(*) FROM keyboxes JOIN channels ON keyboxes.channel_id = channels.channel_id WHERE keyboxes.valid = 1 GROUP BY keyboxes.channel_id')
              channel_stats = c.fetchall()
              
              print(f"\\nSummary: Found {valid_count} valid keyboxes")
              if channel_stats:
                  print("Valid keyboxes by channel:")
                  for channel, count in channel_stats:
                      print(f"- {channel or 'Unknown'}: {count}")
              
              conn.close()
          EOF
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_PHONE: ${{ secrets.TELEGRAM_PHONE }}
          TELEGRAM_SESSION_STRING: ${{ secrets.TELEGRAM_SESSION_STRING }}
          TELEGRAM_CHANNELS: ${{ secrets.TELEGRAM_CHANNELS }}
      
      - name: Run original KeyBoxer scraper
        run: |
          python keyboxer.py
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      
      - name: List discovered keyboxes
        run: |
          echo "Keyboxes discovered from all sources:"
          ls -la keys/
          
          # Count keyboxes
          KEYBOX_COUNT=$(ls -1 keys/*.xml 2>/dev/null | wc -l)
          echo "Total keyboxes found: $KEYBOX_COUNT"
          
          # Validate all keyboxes one more time to ensure they are valid
          python - <<EOF
          import os
          import glob
          from check import keybox_check
          
          valid_count = 0
          invalid_count = 0
          
          for file_path in glob.glob('keys/*.xml'):
              with open(file_path, 'rb') as file:
                  content = file.read()
                  if keybox_check(content):
                      valid_count += 1
                  else:
                      invalid_count += 1
                      print(f"Warning: Invalid keybox detected: {file_path}")
          
          print(f"\nValidation results:")
          print(f"- Valid keyboxes: {valid_count}")
          print(f"- Invalid keyboxes: {invalid_count}")
          EOF
      
      - name: Create combined report
        run: |
          python - <<EOF
          import os
          import json
          import sqlite3
          import glob
          import hashlib
          from datetime import datetime
          
          # Create report data structure
          report = {
              "timestamp": datetime.now().isoformat(),
              "keyboxes_total": len(glob.glob('keys/*.xml')),
              "sources": {
                  "github": 0,
                  "web": 0,
                  "telegram": 0
              },
              "telegram_channels": [],
              "latest_keyboxes": []
          }
          
          # Count Telegram keyboxes
          if os.path.exists('telegram_data.db'):
              conn = sqlite3.connect('telegram_data.db')
              c = conn.cursor()
              
              c.execute('SELECT COUNT(*) FROM keyboxes WHERE valid = 1')
              result = c.fetchone()
              report["sources"]["telegram"] = result[0] if result is not None else 0
              
              try:
                  c.execute('''
                      SELECT 
                          channels.channel_name, 
                          channels.channel_id, 
                          COUNT(keyboxes.id) as keybox_count 
                      FROM 
                          keyboxes 
                      JOIN 
                          channels ON keyboxes.channel_id = channels.channel_id 
                      WHERE 
                          keyboxes.valid = 1 
                      GROUP BY 
                          keyboxes.channel_id
                  ''')
                  
                  for channel_name, channel_id, count in c.fetchall():
                      report["telegram_channels"].append({
                          "name": channel_name or "Unknown",
                          "id": channel_id,
                          "keyboxes": count
                      })
              except Exception as e:
                  print(f"Error getting channel stats: {e}")
                  
              try:
                  c.execute('''
                      SELECT 
                          keyboxes.hash,
                          keyboxes.file_path,
                          messages.date,
                          channels.channel_name
                      FROM 
                          keyboxes 
                      JOIN 
                          messages ON keyboxes.message_id = messages.message_id AND keyboxes.channel_id = messages.channel_id
                      JOIN 
                          channels ON keyboxes.channel_id = channels.channel_id 
                      WHERE 
                          keyboxes.valid = 1 
                      ORDER BY 
                          messages.date DESC
                      LIMIT 10
                  ''')
                  
                  for hash_value, file_path, date, channel_name in c.fetchall():
                      report["latest_keyboxes"].append({
                          "hash": hash_value,
                          "source": f"Telegram: {channel_name or 'Unknown'}",
                          "date": date
                      })
              except Exception as e:
                  print(f"Error getting latest keyboxes: {e}")
                  
              conn.close()
          
          # Save report
          with open('keybox_report.json', 'w') as f:
              json.dump(report, f, indent=2)
              
          print("Created keybox report: keybox_report.json")
          EOF
      
      - name: Create compressed archive of all keyboxes
        run: |
          # Create a zip file with all keyboxes
          # Check if there are any XML files first
          if [ -n "$(find keys -name '*.xml' 2>/dev/null)" ]; then
            zip -r keyboxes.zip keys/
            echo "Created keyboxes.zip with all discovered keyboxes"
            ls -la keyboxes.zip
          else
            echo "No keybox files found to archive"
            # Create empty zip to avoid errors in subsequent steps
            touch empty.txt
            zip keyboxes.zip empty.txt
          fi
      
      - name: Upload to gist
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          # Get current date for description
          DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          
          # Create a simple text summary
          echo "KeyBoxer Report - $DATE" > keybox_summary.txt
          echo "Total keyboxes: $(ls -1 keys/*.xml 2>/dev/null | wc -l)" >> keybox_summary.txt
          
          # Use Python to create the complete gist payload including the zip file
          python - <<EOF
          import json
          import os
          import base64
          from datetime import datetime
          
          # Create the files dictionary for the payload
          files = {}
          
          # Add the summary text file
          with open('keybox_summary.txt', 'r') as f:
              files['keybox_summary.txt'] = {'content': f.read()}
          
          # Add the report JSON file
          try:
              with open('keybox_report.json', 'r') as f:
                  report_content = f.read()
                  files['keybox_report.json'] = {'content': report_content}
          except Exception as e:
              print(f"Error reading report: {e}")
          
          # Add the zip file if it exists
          if os.path.exists('keyboxes.zip'):
              try:
                  # Read and base64 encode the zip file
                  with open('keyboxes.zip', 'rb') as f:
                      zip_content = f.read()
                      zip_base64 = base64.b64encode(zip_content).decode('utf-8')
                      
                  # Add to files dictionary
                  files['keyboxes.zip.base64'] = {'content': zip_base64}
                  print(f"Added zip file to payload (size: {len(zip_content)} bytes, base64: {len(zip_base64)} chars)")
              except Exception as e:
                  print(f"Error adding zip file: {e}")
          
          # Create the full payload
          payload = {
              'description': 'KeyBoxer results - $DATE',
              'public': False,
              'files': files
          }
          
          # Write the properly formatted JSON payload
          with open('gist-payload.json', 'w') as f:
              json.dump(payload, f)
          
          print("Created complete gist payload with all files")
          EOF
          
          # Handle existing or new gist
          GIST_ID_FILE=".gist-id"
          if [ -f "$GIST_ID_FILE" ]; then
            GIST_ID=$(cat "$GIST_ID_FILE")
            echo "Updating existing Gist: $GIST_ID"
            RESPONSE=$(curl -s -X PATCH \
              -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d @gist-payload.json \
              "https://api.github.com/gists/$GIST_ID")
          else
            echo "Creating new Gist"
            RESPONSE=$(curl -s -X POST \
              -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d @gist-payload.json \
              "https://api.github.com/gists")
            
            # Save full response for debugging
            echo "$RESPONSE" > gist-response.json
            
            # Extract the gist ID using grep and sed
            GIST_ID=$(echo "$RESPONSE" | grep -o '"id":\s*"[^"]*"' | head -1 | sed 's/.*"id":\s*"\([^"]*\)".*/\1/')
            
            # Verify we got a valid ID
            if [ -n "$GIST_ID" ]; then
              echo "Extracted Gist ID: $GIST_ID"
              echo "$GIST_ID" > "$GIST_ID_FILE"
            else
              echo "Error: Failed to extract gist ID"
              echo "Response content (first 200 chars):"
              head -c 200 gist-response.json
              exit 1
            fi
          fi
          
          echo "Files uploaded to: https://gist.github.com/$GIST_ID"
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}