name: Run KeyBoxer (Non-Interactive)

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-keyboxer:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install requests python-dotenv beautifulsoup4 lxml cryptography
      
      - name: Create required directories
        run: |
          mkdir -p keys
          touch cache.txt
      
      - name: Create .env file with GitHub token
        run: |
          echo "GITHUB_TOKEN=${{ secrets.PAT_TOKEN }}" > .env
      
      - name: Create non-interactive wrapper
        run: |
          cat > run_noninteractive.py << 'EOL'
          import os
          import sys
          import subprocess
          
          # Set up environment to automatically answer prompts with 'y'
          env = os.environ.copy()
          env['PYTHONIOENCODING'] = 'utf-8'
          
          # Create a process that simulates user input
          process = subprocess.Popen(
              ['python', './keyboxer.py'],
              stdin=subprocess.PIPE,
              stdout=subprocess.PIPE,
              stderr=subprocess.STDOUT,
              text=True,
              env=env
          )
          
          # Process output in real-time and respond to prompts
          while True:
              line = process.stdout.readline()
              if not line and process.poll() is not None:
                  break
                  
              print(line, end='')
              sys.stdout.flush()
              
              # When it asks for input, automatically respond with 'y'
              if "Do you want to delete it? (y/N)" in line:
                  print("Auto-responding: y")
                  process.stdin.write("y\n")
                  process.stdin.flush()
          
          # Return the exit code
          sys.exit(process.returncode)
          EOL
        
      - name: Run KeyBoxer non-interactively
        run: |
          python run_noninteractive.py
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          
      - name: List results
        run: |
          echo "KeyBoxer execution complete"
          echo "Contents of keys directory:"
          ls -la keys/ || echo "No keys directory found"
