name: Run KeyBoxer with Crypto

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-keyboxer:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install requests python-dotenv beautifulsoup4 lxml cryptography
          # Specifically adding cryptography which was missing
          
      - name: Create required directories
        run: |
          mkdir -p keys
          touch cache.txt
      
      - name: Create .env file with GitHub token
        run: |
          echo "GITHUB_TOKEN=${{ secrets.PAT_TOKEN }}" > .env
        
      - name: Run KeyBoxer
        run: |
          python ./keyboxer.py
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          
      - name: List results
        run: |
          echo "KeyBoxer execution complete"
          echo "Contents of keys directory:"
          ls -la keys/ || echo "No keys directory found"
