name: Telegram Channel Discovery (Minimal)

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  id-token: write

jobs:
  discover-channels:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Longer timeout for extensive discovery
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install requests python-dotenv beautifulsoup4 lxml cryptography telethon aiohttp asyncio
      
      - name: Create required directories
        run: |
          mkdir -p keys
          mkdir -p telegram_session
          touch cache.txt
      
      - name: Create .env file with tokens
        run: |
          echo "GITHUB_TOKEN=${{ secrets.PAT_TOKEN }}" > .env
          echo "TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }}" >> .env
          echo "TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }}" >> .env
          echo "TELEGRAM_PHONE=${{ secrets.TELEGRAM_PHONE }}" >> .env
          echo "TELEGRAM_SESSION_STRING=${{ secrets.TELEGRAM_SESSION_STRING }}" >> .env
          echo "GH_TOKEN=${{ github.token }}" >> .env
          
      - name: Run Telegram channel discovery
        run: |
          python - <<EOF
          import os
          import asyncio
          import logging
          from telegram_discovery import setup_database, run_discovery
          
          # Setup logging
          logging.basicConfig(level=logging.INFO)
          
          # DIRECTLY SET THE SESSION STRING
          os.environ["TELEGRAM_SESSION_STRING"] = """${{ secrets.TELEGRAM_SESSION_STRING }}"""
          
          # Initialize database and run discovery
          setup_database()
          asyncio.run(run_discovery(leave_after_completion=True))
          
          # Extract discovered channels for next runs
          import sqlite3
          import json
          from pathlib import Path
          
          db_path = Path("telegram_data.db")
          if db_path.exists():
              conn = sqlite3.connect(db_path)
              c = conn.cursor()
              
              # Get joined channels
              c.execute('SELECT channel_id FROM discovered_channels WHERE join_status = "joined"')
              joined_channels = [row[0] for row in c.fetchall()]
              
              # Get pending channels
              c.execute('SELECT channel_id FROM discovered_channels WHERE join_status = "pending"')
              pending_channels = [row[0] for row in c.fetchall()]
              
              # Create a combined list of all channels
              all_channels = joined_channels.copy()
              
              # Also get already tracked channels
              c.execute('SELECT channel_id FROM channels')
              tracked_channels = [row[0] for row in c.fetchall()]
              
              # Combine all lists without duplicates
              for channel in tracked_channels:
                  if channel not in all_channels:
                      all_channels.append(channel)
              
              # Save results
              channel_data = {
                  "joined": joined_channels,
                  "pending": pending_channels,
                  "all": all_channels
              }
              
              with open('discovered_channels.json', 'w') as f:
                  json.dump(channel_data, f, indent=2)
              
              print(f"\nDiscovery Summary:")
              print(f"- Joined channels: {len(joined_channels)}")
              print(f"- Pending channels: {len(pending_channels)}")
              print(f"- Total tracked channels: {len(all_channels)}")
              
              conn.close()
          EOF
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_PHONE: ${{ secrets.TELEGRAM_PHONE }}
          TELEGRAM_SESSION_STRING: ${{ secrets.TELEGRAM_SESSION_STRING }}
      
      - name: Run Keyboxer on discovered channels
        run: |
          python - <<EOF
          import os
          import asyncio
          import json
          import logging
          from telegram_crawler import setup_database, add_channel, one_time_scrape
          
          # Setup logging
          logging.basicConfig(level=logging.INFO)
          
          # DIRECTLY SET THE SESSION STRING
          os.environ["TELEGRAM_SESSION_STRING"] = """${{ secrets.TELEGRAM_SESSION_STRING }}"""
          
          # Initialize database
          setup_database()
          
          # Add all discovered channels to tracking
          discovered_file = 'discovered_channels.json'
          if os.path.exists(discovered_file):
              with open(discovered_file, 'r') as f:
                  channel_data = json.load(f)
                  
              # Add joined channels to tracking
              for channel in channel_data.get('joined', []):
                  add_channel(channel)
                  print(f"Added joined channel {channel} to tracking")
                  
              # Also add existing tracked channels from secret
              telegram_channels = os.environ.get('TELEGRAM_CHANNELS')
              if telegram_channels:
                  channels_to_add = json.loads(telegram_channels)
                  for channel in channels_to_add:
                      add_channel(channel)
                      print(f"Added channel {channel} from secret to tracking")
                      
              # Run the crawler on all tracked channels
              asyncio.run(one_time_scrape())
          else:
              print("No discovered channels file found")
          EOF
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_PHONE: ${{ secrets.TELEGRAM_PHONE }}
          TELEGRAM_SESSION_STRING: ${{ secrets.TELEGRAM_SESSION_STRING }}
          TELEGRAM_CHANNELS: ${{ secrets.TELEGRAM_CHANNELS }}
      
      - name: Update GitHub secret with discovered channels
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          if [ -f "discovered_channels.json" ]; then
            # Extract the "all" channels array and format it for GitHub secrets
            ALL_CHANNELS=$(cat discovered_channels.json | jq -c '.all')
            
            # Using GitHub CLI to update the secret
            echo "Updating TELEGRAM_CHANNELS secret with discovered channels"
            GH_TOKEN="${{ github.token }}" gh secret set TELEGRAM_CHANNELS --body="$ALL_CHANNELS"
            
            echo "Secret updated successfully"
          else
            echo "No discovered channels file found, skipping secret update"
          fi
      
      - name: List discovered keyboxes
        run: |
          echo "Keyboxes discovered from all sources:"
          ls -la keys/
          
          # Count keyboxes
          KEYBOX_COUNT=$(ls -1 keys/*.xml 2>/dev/null | wc -l)
          echo "Total keyboxes found: $KEYBOX_COUNT"
      
      - name: Commit and push keyboxes
        run: |
          # Configure git
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Check if there are any XML files to add
          if [ -n "$(find keys -name '*.xml' 2>/dev/null)" ]; then
            # Add discovered keyboxes
            git add keys/*.xml
            
            # Add discovered channels JSON if it exists
            if [ -f "discovered_channels.json" ]; then
              git add discovered_channels.json
            fi
            
            # Commit and push changes
            git commit -m "Add newly discovered keyboxes [automated]"
            git push
            echo "Committed and pushed new keyboxes"
          else
            echo "No keybox files found to commit"
          fi
